config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :forecasts
    resources :locations do
       resources :comments
    end
    
    root 'locations#find'
    #root 'forecasts#index'
    
    
    post "/", to: 'locations#submit', as: "submit"
    post 'locations/:id/comments', to: 'comments#create', as: "comment"
    #delete 'locations/:id/comments/:id', to: 'comments#destroy', as: "delete"
    
    
    get '/currentWeather' => 'locations#find'
    
    
    #get '/users/sign_in' => 'devise/sessions#new'
    #get '/users/sign_up' => 'devise/registrations#new'
    #get '/users/sign_out' => 'devise/sessions#destroy'
    
    
    get '/about' => 'forecasts#about'
    get '/welcome' => 'forecasts#index'
    get '/forecast' => 'forecasts#show'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :location
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
     before_action :authenticate_user! 
    
    #generates comment based on location id
    #response will be the rendering of an html partial with local variables passed in
    
    def index
        @comments = Comment.all
        @location = Location.find params[:location_id]
    end
    
    def create
        @location = Location.find(params[:location_id])
        @comment = @location.comments.create(comment_params)
    
        respond_to do |format|
            format.html { render :partial => "comments/comment",  locals: {comment: @comment} }
        
       end
    end
    
    def destroy
        Comment.find(params[:id]).destroy
        redirect_to root_path
        
    end

    private

    #sets the attributes that are allowed for a comment
    def comment_params
        params.require(:comment).permit(:name, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-display">
    <div class="pull-left comment_content">
	<p>
		<strong>Name:</strong>
	      <%= comment.name %>
	</p>
	<p>
		<strong>Comment:</strong>
	     <%= comment.body %>
	</p>
	<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= current_user.email %></small></p></small></p>
    </div>
    <div class="btn-group pull-left"> 
        <% if user_signed_in? %>
        <%= link_to 'Destroy', location_comment_path(@location, comment), method: :delete, data: { confirm: 'Are you sure?' }, 
                        class: "btn btn-sm btn-default" %>
         <% end %>
    
    </div>
 </div> 
	

app/views/comments/_form.html.erb
<div class="comment-list">
<% @location.comments.each do |comment| %>

<%= render partial: "comments/comment", locals: {comment: comment}  %>

<% end %>
</div>

<div class="comment-form">

	<h1>What Would You Wear Today?</h1>
	<%= form_for :comment, url: comment_url(id: @location), html: {class: 'submit-comment'} do |f| %>
	<p class="comment-name">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p class="comment-body">
		<%= f.label :comment %><br>
		<%= f.text_area :body %>
	</p>
	<p class="submit">
		<%= f.submit 'Submit' %>
	</p>
   <% end %>
</div>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Body</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.location_id %></td>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>